package com.anosym.tranglo.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.7-b01 Generated source version: 2.2
 *
 */
@WebService(name = "EPin_ReloadSoap", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE)
@XmlSeeAlso({
  ObjectFactory.class
})
public interface EPinReloadSoap {

  /**
   *
   * @param userID
   * @param transID
   * @param prodCode
   * @param deno
   * @param destNo
   * @param sourceNo
   * @param password
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Request_Reload", action = EPinReload.EPINRELOAD_TARGET_NAMESPACE+"/Request_Reload")
  @WebResult(name = "Request_ReloadResult", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE)
  @RequestWrapper(localName = "Request_Reload", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.RequestReload")
  @ResponseWrapper(localName = "Request_ReloadResponse", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.RequestReloadResponse")
  public String requestReload(
          @WebParam(name = "sourceNo", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String sourceNo,
          @WebParam(name = "destNo", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String destNo,
          @WebParam(name = "prodCode", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String prodCode,
          @WebParam(name = "deno", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) int deno,
          @WebParam(name = "UserID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String userID,
          @WebParam(name = "Password", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String password,
          @WebParam(name = "transID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String transID);

  /**
   *
   * @param userID
   * @param transID
   * @param prodCode
   * @param deno
   * @param destNo
   * @param sourceNo
   * @param password
   * @return returns
   * com.anosym.tranglo.wsdl.RequestReloadAmountNewResponse.RequestReloadAmountNewResult
   */
  @WebMethod(operationName = "Request_ReloadAmount_New", action = EPinReload.EPINRELOAD_TARGET_NAMESPACE+"/Request_ReloadAmount_New")
  @WebResult(name = "Request_ReloadAmount_NewResult", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE)
  @RequestWrapper(localName = "Request_ReloadAmount_New", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.RequestReloadAmountNew")
  @ResponseWrapper(localName = "Request_ReloadAmount_NewResponse", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.RequestReloadAmountNewResponse")
  public com.anosym.tranglo.wsdl.RequestReloadAmountNewResponse.RequestReloadAmountNewResult requestReloadAmountNew(
          @WebParam(name = "sourceNo", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String sourceNo,
          @WebParam(name = "destNo", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String destNo,
          @WebParam(name = "prodCode", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String prodCode,
          @WebParam(name = "deno", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String deno,
          @WebParam(name = "UserID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String userID,
          @WebParam(name = "Password", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String password,
          @WebParam(name = "transID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String transID);

  /**
   *
   * @return returns int
   */
  @WebMethod(operationName = "Ping", action = EPinReload.EPINRELOAD_TARGET_NAMESPACE+"/Ping")
  @WebResult(name = "PingResult", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE)
  @RequestWrapper(localName = "Ping", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.Ping")
  @ResponseWrapper(localName = "PingResponse", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.PingResponse")
  public int ping();

  /**
   *
   * @param userID
   * @param transID
   * @param password
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Transaction_Inquiry", action = EPinReload.EPINRELOAD_TARGET_NAMESPACE+"/Transaction_Inquiry")
  @WebResult(name = "Transaction_InquiryResult", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE)
  @RequestWrapper(localName = "Transaction_Inquiry", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.TransactionInquiry")
  @ResponseWrapper(localName = "Transaction_InquiryResponse", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.TransactionInquiryResponse")
  public String transactionInquiry(
          @WebParam(name = "transID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String transID,
          @WebParam(name = "UserID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String userID,
          @WebParam(name = "Password", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String password);

  /**
   *
   * @param userID
   * @param transID
   * @param password
   * @return returns
   * com.anosym.tranglo.wsdl.TransactionInquiryDetailsResponse.TransactionInquiryDetailsResult
   */
  @WebMethod(operationName = "Transaction_Inquiry_Details", action = EPinReload.EPINRELOAD_TARGET_NAMESPACE+"/Transaction_Inquiry_Details")
  @WebResult(name = "Transaction_Inquiry_DetailsResult", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE)
  @RequestWrapper(localName = "Transaction_Inquiry_Details", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.TransactionInquiryDetails")
  @ResponseWrapper(localName = "Transaction_Inquiry_DetailsResponse", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.TransactionInquiryDetailsResponse")
  public com.anosym.tranglo.wsdl.TransactionInquiryDetailsResponse.TransactionInquiryDetailsResult transactionInquiryDetails(
          @WebParam(name = "transID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String transID,
          @WebParam(name = "UserID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String userID,
          @WebParam(name = "Password", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String password);

  /**
   *
   * @param userID
   * @param transID
   * @param password
   * @return returns com.anosym.tranglo.wsdl.EWalletInquiryResponse.EWalletInquiryResult
   */
  @WebMethod(operationName = "EWallet_Inquiry", action = EPinReload.EPINRELOAD_TARGET_NAMESPACE+"/EWallet_Inquiry")
  @WebResult(name = "EWallet_InquiryResult", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE)
  @RequestWrapper(localName = "EWallet_Inquiry", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.EWalletInquiry")
  @ResponseWrapper(localName = "EWallet_InquiryResponse", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.EWalletInquiryResponse")
  public com.anosym.tranglo.wsdl.EWalletInquiryResponse.EWalletInquiryResult eWalletInquiry(
          @WebParam(name = "transID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String transID,
          @WebParam(name = "UserID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String userID,
          @WebParam(name = "Password", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String password);

  /**
   *
   * @param userID
   * @param transID
   * @param prodCode
   * @param deno
   * @param password
   * @return returns com.anosym.tranglo.wsdl.ProductPriceInquiryResponse.ProductPriceInquiryResult
   */
  @WebMethod(operationName = "Product_Price_Inquiry", action = EPinReload.EPINRELOAD_TARGET_NAMESPACE+"/Product_Price_Inquiry")
  @WebResult(name = "Product_Price_InquiryResult", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE)
  @RequestWrapper(localName = "Product_Price_Inquiry", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.ProductPriceInquiry")
  @ResponseWrapper(localName = "Product_Price_InquiryResponse", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.ProductPriceInquiryResponse")
  public com.anosym.tranglo.wsdl.ProductPriceInquiryResponse.ProductPriceInquiryResult productPriceInquiry(
          @WebParam(name = "transID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String transID,
          @WebParam(name = "UserID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String userID,
          @WebParam(name = "Password", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String password,
          @WebParam(name = "prodCode", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String prodCode,
          @WebParam(name = "deno", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String deno);

  /**
   *
   * @param userID
   * @param transID
   * @param prodCode
   * @param deno
   * @param destNo
   * @param sourceNo
   * @param password
   * @return returns java.lang.String
   */
  @WebMethod(operationName = "Request_Reload_New", action = EPinReload.EPINRELOAD_TARGET_NAMESPACE+"/Request_Reload_New")
  @WebResult(name = "Request_Reload_NewResult", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE)
  @RequestWrapper(localName = "Request_Reload_New", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.RequestReloadNew")
  @ResponseWrapper(localName = "Request_Reload_NewResponse", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.RequestReloadNewResponse")
  public String requestReloadNew(
          @WebParam(name = "sourceNo", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String sourceNo,
          @WebParam(name = "destNo", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String destNo,
          @WebParam(name = "prodCode", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String prodCode,
          @WebParam(name = "deno", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String deno,
          @WebParam(name = "UserID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String userID,
          @WebParam(name = "Password", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String password,
          @WebParam(name = "transID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String transID);

  /**
   *
   * @param userID
   * @param transID
   * @param prodCode
   * @param deno
   * @param destNo
   * @param sourceNo
   * @param password
   * @return returns com.anosym.tranglo.wsdl.RequestReloadAmountResponse.RequestReloadAmountResult
   */
  @WebMethod(operationName = "Request_ReloadAmount", action = EPinReload.EPINRELOAD_TARGET_NAMESPACE+"/Request_ReloadAmount")
  @WebResult(name = "Request_ReloadAmountResult", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE)
  @RequestWrapper(localName = "Request_ReloadAmount", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.RequestReloadAmount")
  @ResponseWrapper(localName = "Request_ReloadAmountResponse", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE, className = "com.anosym.tranglo.wsdl.RequestReloadAmountResponse")
  public com.anosym.tranglo.wsdl.RequestReloadAmountResponse.RequestReloadAmountResult requestReloadAmount(
          @WebParam(name = "sourceNo", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String sourceNo,
          @WebParam(name = "destNo", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String destNo,
          @WebParam(name = "prodCode", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String prodCode,
          @WebParam(name = "deno", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) int deno,
          @WebParam(name = "UserID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String userID,
          @WebParam(name = "Password", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String password,
          @WebParam(name = "transID", targetNamespace = EPinReload.EPINRELOAD_TARGET_NAMESPACE) String transID);
}
